### ISSUE TITLE
ios memory leak on takePicture

### ISSUE THREAD

**Issue by suddrey** [cordova-plugin-camera-preview/cordova-plugin-camera-preview#200]
The ios version of this plugin appears to have a rather serious memory leak relating to the takePicture method.

Taking successive photos results in the amount of memory being used by the application increasing by a rate of roughly 20mb per image. I'm assuming that the increase is related to the resolution of the images being captured, which is what makes it more noticeable.

I also suspect that this is the most likely cause of Issue #162 as my app crashes after three or four images have been captured.

**Comment by westonganger** [comment]
Just to confirm you are using master? not the last version on npm.

Do you have any idea what might be causing this? I just updated master which removes an unnecessary dispatch group in the ios code, but that likely wont fix it but its possible.

**Comment by suddrey** [comment]
Yes I'm using master at present. I've attached an image of inspector. It seems like images aren't being garbage collected. 

I'm not really too up with the details of objective-C however so this is pure conjecture.

![screen shot 2017-03-06 at 2 58 48 pm](https://cloud.githubusercontent.com/assets/10663573/23597348/c754f74c-027d-11e7-982a-6e0a896e21cb.png)

**Comment by westonganger** [comment]
Okay thanks for pointing me in the right direction I search for CGImage memory leaks and found this. http://stackoverflow.com/questions/4567465/cgimageref-memory-leak

Will look into doing this later.

**Comment by westonganger** [comment]
I just made a fix which releases the CGImageRef whenever possible. There was one that I didn't specify to release as I was unsure about it so please provide me another screenshot showing your findings.

**Comment by suddrey** [comment]
It seems that I'm not getting an EX_BAD_ACCESS error. Again I've tried this on both an older and newer device.

**Comment by westonganger** [comment]
So does that mean the problem was solved?

**Comment by suddrey** [comment]
Sorry, typo, that should read I'm now getting an EX_BAD_ACCESS error.

**Comment by westonganger** [comment]
One of the lines in the last fix was incorrect. I have now updated master.

**Comment by suddrey** [comment]
I'm still getting the EXC_BAD_ACCESS error but it now only appears after I take a second photo.

**Comment by westonganger** [comment]
Just switched the release call. Can you you try again with the latest.

**Comment by suddrey** [comment]
No luck I'm afraid.

![screen shot 2017-03-07 at 3 51 23 pm](https://cloud.githubusercontent.com/assets/10663573/23643517/0581e892-034e-11e7-911b-8789e4a21bc1.png)

**Comment by Tawsif** [comment]
Any Update on this?

Please guys consider this issue as critical. I am not finding any solution for this. I am striving for this since 1 year.

Please provide solution or cause of the issue.

**Comment by jlongman** [comment]
I think a double-release is happening:  

Line 314 (or so, may have edits, near tip which was e32de2326) in `CGImageRotated` produces the `resultFinalImage` but also calls `CFAutoRelease` on the `resultFinalImage`.  Later in `invokeTakePicture`, line 387 (or so), the image is released with `CGImageRelease(resultFinalImage);`.

I haven't gotten as far as checking whether the memory leak is gone however, but it's possible a thirdparty is retaining something somewhere else.

**Comment by jlongman** [comment]
I didn't look and don't know the code well enough to know whether the `CGImageRotated` is used elsewhere - if it's not it might be worth removing the `CFAutoRelease` call from that.

Otherwise looking at the Instruments tool - which I am new to, so caveat lector, it looks like the leak is gone.  

I took five pictures, 
- CGRaster data permanent was 121MB, transient is 32K later at steady state.
- CFString (immutable) data permanent was 52.29MB, transient is 2.14K later at steady state.

**Comment by westonganger** [comment]
Updated master using your findings let me know.

**Comment by suddrey** [comment]
I was still getting crashes after pulling the latest version from master.

However, commenting out line 314 (see below) has fixed the crash for me. Jongman was correct in that this was a double release issue. It seems that releasing the resource in rotateImage and then releasing it in invokeTakePicture resulted in the crash.

Having made this change, and with your previous changes, I am no longer having any memory leaks or crashes. 

314: CFAutorelease((CFTypeRef)rotatedCGImage); <- Should be removed

**Comment by Tawsif** [comment]
Hi @suddrey 

CFAutorelease((CFTypeRef)rotatedCGImage); from which file this code should be removed can you please tell me the file name ?

**Comment by JadeSinner** [comment]
CameraPreview.m

**Comment by Tawsif** [comment]
Hi guys,

I have removed `CFAutorelease((CFTypeRef)rotatedCGImage);` , but it still crashes on my device after 20 successive captures.

I tested on iPhone 6 device.

I have updated on my npm repository at [](https://www.npmjs.com/package/cordova-camera-custom) you all can review my code changes there.

**Comment by westonganger** [comment]
Okay I have a better understanding of what was happening here now. I just updated master. Hopefully both the crashing and memory issues are fixed.

**Comment by vinimendes3** [comment]
My app is closing when I take a picture, only in iOS. :(

**Comment by Tawsif** [comment]
I have also provided the camera app developed using this plugin to apple with a system diagnose of my device.

**They gave following reply:**

Engineering has provided the following feedback regarding this issue: 

Thanks for the new sysdiagnose.

There is a jetsam event JetsamEvent-2017-03-01-103903.ips.synced. CameraPreviewDemo is killed because it’s exceeding the memory limit. It looks like the app needs to manage the memory so that it won’t get killed.

Now I dont know where the hell my memory fills up and crashes the application after successive captures.

This may help you guys in the concern of crash. Please help

**Comment by jlongman** [comment]
@tawsif It's quite possible you are leaking within your code and it's not the plugin.   Also you need to include a git revision number when you make a claim like this because the code is changing rapidly and maybe you're using a "broken" version.  e.g. the latest code, tip as I write this is e334ca3e1.  If you're not running from git then you have an old version.

Additionally, in Xcode you should open the Instruments tool and look at leaks:

- start your app from Xcode
- in Xcode click `Xcode`->`Open Developer Tool`->`Instruments` 
- in Instruments click `Leaks`
- on the top left change your host computer to either the apple device or the simulator you are running
- select your app on the device or simulator
- hit the red button to start profiling memory
- go to your app and take pictures
- sort the bottom table by `Persistent Bytes`

You will likely see what type of object is the leak as it will likely consume the most RAM.  This will help find the leak.

**Comment by Tawsif** [comment]
Hi @jlongman 

As per your suggestion I have used plugin from git **e334ca3** but the app still crashes.
**FYI. :** In my demo project CameraPreviewDemo I have used 2 pages where first page has a button named **Open Camera** and second page has camera preview displayed with a **Capture Button** 

Thats it !!!

Now why does the app crash which has just 2 pages and 2 buttons and a Camera Preview in the application?

When I dont use Camera and operate the app for hours it does not crash.

And So I doubt the Plugin Code.

Now I am thinking of debugging and profiling the app's memory allocation as you suggested to find the real cause.

I can also provide you the Camera Preview Demo Project Code if you need.

**Comment by jlongman** [comment]
@tawsif what you do with the pictures taken also matters.  e.g. in my app they are passed to a meteor server and then uploaded to S3.  You could maybe create a stub - a piece of code that isn't the plugin but acts like it - that generates an image without the plugin and see if the memory leak is still present.

I also use the tap on the preview to take the picture so that is different than your scenario.

But maybe you should publish the demo project somewhere, it might be useful.

**Comment by Tawsif** [comment]
@jlongman @westonganger @suddrey  I tested the demo project [cordova-plugin-camera-preview-sample-app](https://github.com/cordova-plugin-camera-preview/cordova-plugin-camera-preview-sample-app)

Same thing happens with this app too. It crashes after 20 to 25 successive image captures.
Steps to reproduce:
1) Tap on 'Start Camera Above HTML
2) Change preview size to FullScreen
3) Switch Camera to 'Back Camera'
4) Now start taking picture continuously 30 times, and it crashes after 30 image captures at some point.

I have also debugged this app in XCode, and it shows memory usage up to 450 mb and it increases continuously until the app crashes.

I have **iPhone 6 Plus device** with **iOS 10.3**

**Comment by jlongman** [comment]
I may have reproduced your bug, but first your Steps To Reproduce are impossible, they must be:

1. Tap on 'Start Camera Above HTML
2. Switch Camera to 'Back Camera'
3. Change preview size to FullScreen
4. Now start taking picture continuously 30 times, and it crashes after 30 image captures at some point.

Because you can't change to the Back Camera once FullScreen - as far as I know.  In any case, that's how I reproduced it.

Second, this is how I ensured I was using the tip of the plugin:

    git clone https://github.com/cordova-plugin-camera-preview/cordova-plugin-camera-preview-sample-app.git
    cd cordova-plugin-camera-preview-sample-app/
    cordova platform add ios
    cordova build ios
    cordova plugin remove cordova-plugin-camera-preview
    cordova plugin add https://github.com/cordova-plugin-camera-preview/cordova-plugin-camera-preview.git#568358853a539e53d1e48f15039338958a9eb209 # current tip 
    rm -rf platforms/ plugins/
    cordova platform add ios
    cordova build ios
    open platforms/ios/cordova-plugin-camera-sample-app.xcodeproj/

I then added my dev profile and the NSCameraUsageETCETC in the build settings.

My first attempt I let the picture reduce to steady state (i.e. took pictures slowly) and there was no leak.
My second attempt I continuously tapped the screen to get the leak to happen.  It definitely leaked and crashed.
My third attempt I tapped a couple of times then stopped, enough so it wouldn't crash but would take multiple pictures.  There was leaking but the memory recovered to a reasonable (if not the same as 1st attempt, about 10M more) level.

it looks like this:

```
2017-04-07 12:44:58.390527-0400 cordova-plugin-camera-sample-app[4848:1065210] handleTakePictureTap
2017-04-07 12:44:58.590764-0400 cordova-plugin-camera-sample-app[4848:1065210] handleTakePictureTap
2017-04-07 12:44:58.788893-0400 cordova-plugin-camera-sample-app[4848:1065210] handleTakePictureTap
2017-04-07 12:44:58.956389-0400 cordova-plugin-camera-sample-app[4848:1065210] handleTakePictureTap
2017-04-07 12:44:59.141557-0400 cordova-plugin-camera-sample-app[4848:1065210] handleTakePictureTap
2017-04-07 12:44:59.205683-0400 cordova-plugin-camera-sample-app[4848:1065210] Done creating still image
2017-04-07 12:45:01.153112-0400 cordova-plugin-camera-sample-app[4848:1065210] Invalid callback id received by sendPluginResult
2017-04-07 12:45:01.163255-0400 cordova-plugin-camera-sample-app[4848:1065210] Done creating still image
2017-04-07 12:45:03.083081-0400 cordova-plugin-camera-sample-app[4848:1065210] Invalid callback id received by sendPluginResult
2017-04-07 12:45:03.092684-0400 cordova-plugin-camera-sample-app[4848:1065210] Done creating still image
2017-04-07 12:45:05.070293-0400 cordova-plugin-camera-sample-app[4848:1065210] Invalid callback id received by sendPluginResult
2017-04-07 12:45:05.083366-0400 cordova-plugin-camera-sample-app[4848:1065210] Done creating still image
2017-04-07 12:45:07.222325-0400 cordova-plugin-camera-sample-app[4848:1065210] Invalid callback id received by sendPluginResult
2017-04-07 12:45:07.236590-0400 cordova-plugin-camera-sample-app[4848:1065210] Done creating still image
2017-04-07 12:45:09.034308-0400 cordova-plugin-camera-sample-app[4848:1065210] Invalid callback id received by sendPluginResult
2017-04-07 12:45:09.072827-0400 cordova-plugin-camera-sample-app[4848:1065210] handleTakePictureTap
2017-04-07 12:45:09.196858-0400 cordova-plugin-camera-sample-app[4848:1065210] handleTakePictureTap
2017-04-07 12:45:09.306197-0400 cordova-plugin-camera-sample-app[4848:1065210] handleTakePictureTap
2017-04-07 12:45:09.314675-0400 cordova-plugin-camera-sample-app[4848:1065210] handleTakePictureTap
2017-04-07 12:45:09.325526-0400 cordova-plugin-camera-sample-app[4848:1065210] handleTakePictureTap
2017-04-07 12:45:09.340988-0400 cordova-plugin-camera-sample-app[4848:1065210] handleTakePictureTap
2017-04-07 12:45:09.561312-0400 cordova-plugin-camera-sample-app[4848:1065210] Done creating still image
2017-04-07 12:45:10.527934-0400 cordova-plugin-camera-sample-app[4848:1065210] Invalid callback id received by sendPluginResult
2017-04-07 12:45:10.571976-0400 cordova-plugin-camera-sample-app[4848:1065210] Done creating still image
2017-04-07 12:45:11.879005-0400 cordova-plugin-camera-sample-app[4848:1065210] Invalid callback id received by sendPluginResult
2017-04-07 12:45:11.888627-0400 cordova-plugin-camera-sample-app[4848:1065210] Done creating still image
2017-04-07 12:45:13.831722-0400 cordova-plugin-camera-sample-app[4848:1065210] Invalid callback id received by sendPluginResult
2017-04-07 12:45:13.887938-0400 cordova-plugin-camera-sample-app[4848:1065210] Done creating still image
2017-04-07 12:45:14.700631-0400 cordova-plugin-camera-sample-app[4848:1065210] Invalid callback id received by sendPluginResult
2017-04-07 12:45:14.709107-0400 cordova-plugin-camera-sample-app[4848:1065210] Done creating still image
2017-04-07 12:45:15.742483-0400 cordova-plugin-camera-sample-app[4848:1065210] Invalid callback id received by sendPluginResult
2017-04-07 12:45:15.753797-0400 cordova-plugin-camera-sample-app[4848:1065210] Done creating still image
2017-04-07 12:45:16.842170-0400 cordova-plugin-camera-sample-app[4848:1065210] Invalid callback id received by 
```

This pretty clearly indicates the pictures are being processed by the plugin but are not technically leaked - they're just queued and then handled late - as long as the app doesn't use too much memory leading to the OS killing it.  

Despite that technicality it is still **Very Bad**™ if it crashes the app.

There are two ways to fix this:  

- the plugin could say only one picture can be taken until the callback happens.  This could also be _n_ pictures if the user needed that - maybe you need to take, say, 3 successive images which won't blow the memory but still is useful to the user.
- the app could disable taking a picture until the callback happens.  Similarly a count could be used.

I think maybe both make sense, but the plugin-side _should_ be done.

**Comment by westonganger** [comment]
So your saying we need to a `setMaximumConcurrentPictures` method which defaults to 3.

**Comment by jlongman** [comment]
A default of 1 may be fine, and is safest because it's the minimal memory footprint.

Personally concurrent pictures seem an exceptional case, but my use case is static subjects so you're not going to be taking a lot at the same time. Other apps may have more dynamic behaviour.

**Comment by westonganger** [comment]
Sometimes when I take photos I like to snap a few quick just so one of the them actually turns out good. 

But maybe your right 1 should be default and we allow the developer to knowingly change it. We could provide a warning in the readme about memory.

**Comment by bengovernment** [comment]
I'm seeing a similar issue today on ipad mini (gen 4) with a cordova based third party plugin. is there any recourse at this point?

**Comment by PicklesAU** [comment]
Hi, i got simmilar issue,
i take picture 1 at a time, (takepicture, then reopen the page take another pic) 
but this still crash after taking the 11th pic, 
I'm using Iphone 8

**Comment by ryaa** [comment]
This problem could be related to https://github.com/cordova-plugin-camera-preview/cordova-plugin-camera-preview/issues/604
