### ISSUE TITLE
Save to File

### ISSUE THREAD

**Issue by frankzhangxd** [cordova-plugin-camera-preview/cordova-plugin-camera-preview#482]
I try to save picture after taking photo, so I set option storeToFile to ture, here is the script `CameraPreview.startCamera({ x: 50, y: 100, width: 400, height: 400, toBack: false, previewDrag: false, tapPhoto: false, disableExifHeaderStripping: true, storeToFile: true }) `

and after taking picture, I call my script:
CameraPreview.takePicture({width:640, height:640, quality: 85}, function(path){
                    alert('file://' + path);
                  });
```
it seems return base64 encoded data instead of url, what I did wrong and where I can find the actual picture on the device?

**Comment by RoseShazwan** [comment]
Got same issue. any fixes or workaround?

**Comment by RoseShazwan** [comment]
hi. i fixed the problem my removing the plugin and reinstall using the master version with latest fixes and features. stable release doesn't have that storetofile features yet. hope it helps

**Comment by rrath-edr** [comment]
@RoseShazwan 
I am using ionic 4. Have removed the plugin and added the master like this
ionic cordova plugin add https://github.com/cordova-plugin-camera-preview/cordova-plugin-camera-preview.git

But I am still not seeing the storeTOFile option available. Can you please tell me how where I am doing wrong.

Config.xml 
 <plugin name="cordova-plugin-camera-preview" spec="git+https://github.com/cordova-plugin-camera-preview/cordova-plugin-camera-preview.git">

**Comment by RobinGiel** [comment]
@rrath-edr  that's because StoreToFile is not exposed in the ionic native yet. You need reach this option straight from the cordova plugin. I'm going to try to do that and if it works I'll share it here

**Comment by faraz9x** [comment]
Did you guys got this sorted out? Iam also getting base64 instead of the fileURI
